apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../base/bookings/deployment.yaml
- ../../base/releases/deployment.yaml
- ../../base/xray/daemonset.yaml

images:
- name: crowdunlocked/bookings
  newTag: dev-latest
- name: crowdunlocked/releases
  newTag: dev-latest

patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
